name: 'Yan Create Tag'
description: 'Greet someone and record the time'
inputs:
  tag: 
     description: "Generated tag"
     required: true
  message: 
     description: "tag message"
     required: true
  commit: 
     description: "commit sha"
     required: true 
  token:
    required: true
    default: ${{ github.token }}
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
